name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Linting
      run: |
        poetry run mypy --install-types --non-interactive telathbot
        poetry run pylint telathbot
        poetry run black --check telathbot tests
    - name: Build local dev stack
      run: docker-compose -f tests/local_dev/docker-compose.yaml up -d
    - name: Run tests
      run: |
        cp .env-local .env
        poetry run pytest
    # - name: "Upload coverage to Codecov"
    #   uses: codecov/codecov-action@v2
    #   with:
    #     fail_ci_if_error: true
    #     files: ./test_results/cov.xml
    #     token: ${{ secrets.CODECOV_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test_results
