name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Linting
      run: |
        poetry run mypy --install-types --non-interactive telathbot
        poetry run pylint telathbot
        poetry run isort . --check --diff
        poetry run black --check --target-version py310 telathbot tests
    - name: Run tests
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        docker-compose -f tests/local_dev/docker-compose.yaml up -d
        sleep 10
        cp .env-local .env
        poetry run pytest
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: test-results/results.xml
    - name: Send coverage to Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        poetry run coveralls --service=github
    - uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test_results
